schedule = [
    ['sleeping', 300],
    ['putting on running shoes.', 5],
    ['stretching before jog.', 10],
    ['jogging to a nearby park.', 20],
    ['meditating during the jog.', 15],
    ['hydrating after the jog.', 10],
    ['hydrating after the jog.', 5],
    ['stretching after the jog.', 10],
    ['meditating during a short break.', 15],
    ['visualizing goals for the day.', 10],
    ['taking deep breaths to focus.', 5],
    ['mentally preparing for work.', 15],
    ['Arriving at the café and clocking in.', 5],
    ['Reviewing daily specials and promotions on a whiteboard.', 10],
    ['Preparing for morning rush by restocking supplies and adjusting equipment.', 15],
    ['Greeting regular customers and making small talk to build rapport.', 20],
    ['Restocking coffee beans, sugar, and creamers on the counter.', 10],
    ['Restocking coffee beans, sugar, and creamers on the counter.', 10],
    ['Reviewing daily specials and promotions on a whiteboard.', 15],
    ['Preparing for morning rush by adjusting equipment and setting up condiments.', 20],
    ['Greeting regular customers and making small talk to build rapport.', 25],
    ['Taking orders and operating the cash register efficiently.', 30],
    ['Preparing drinks according to customer requests, including espresso shots and pour-overs.', 35],
    ['Maintaining a clean workspace by wiping down surfaces and disposing of waste.', 20],
    ['Handling customer complaints and resolving issues promptly.', 25],
    ['Restocking milk, syrups and other supplies as needed.', 15],
    ['Preparing for the lunch rush by replenishing snacks and refreshments.', 20],
    ['Taking a short break to stretch and recharge before the next wave of customers arrives.', 15],
    ['Managing inventory levels and reporting any discrepancies to management.', 25],
    ['Preparing for a potential rush by setting up extra equipment and supplies.', 20],
    ['Continuing to take orders and operate the cash register efficiently.', 30],
    ['Finalizing preparations for the lunch service and ensuring everything is ready to go.', 10],
    ['Taking a final break before transitioning to administrative tasks at 2 PM.', 45],
    ['Reviewing daily sales and revenue reports on a computer.', 10],
    ['Checking inventory levels of coffee beans, milk, and other essential supplies.', 15],
    ['Responding to supplier inquiries about new shipment arrivals.', 20],
    ['Updating the workshop schedule for the upcoming week on a whiteboard.', 10],
    ["Taking a final moment to review the day's tasks and prioritize administrative duties.", 5],
    [': 1) Checking and responding to urgent emails regarding supplier inquiries.', 15],
    ['Reviewing inventory levels and updating the stock list on a spreadsheet.', 20],
    ['Planning and scheduling workshops for the upcoming week.', 25],
    ['Updating supplier contact information in the database.', 10],
    ['Reviewing sales data to inform menu and inventory decisions.', 15],
    ['Finalizing preparations for the "Coffee & Community" fundraiser on April 10th, 2025.', -25],
    ['Updating supplier contact information in the database.', 20],
    ['Reviewing inventory levels and updating the stock list on a spreadsheet.', 25],
    ['Planning and scheduling workshops for the upcoming week.', 30],
    ['Checking and responding to urgent emails regarding supplier inquiries.', 15],
    ['Reviewing sales data to inform menu and inventory decisions.', 10],
    ['Finalizing preparations for the "Coffee & Community" fundraiser on April 10th, 2025.', 20],
    ['Responding to emails from aspiring baristas with questions about brewing techniques.', 10],
    ['Reviewing online forum posts on urban agriculture best practices.', 15],
    ['Creating a video tutorial on latte art for his online community.', 20],
    ['Planning a workshop on sustainable coffee sourcing for the "Coffee & Community" fundraiser.', 10],
    ["Wrapping up work on urban gardening project by updating his garden's irrigation system.", 5],
    ['Checking the current weather forecast and adjusting irrigation system settings accordingly.', 10],
    ['Reviewing notes on soil moisture levels and making necessary adjustments to prevent overwatering.', 15],
    ["Scheduling a delivery of organic fertilizer for the garden's vegetable beds.", 20],
    ['Researching new irrigation system designs that are more efficient and eco-friendly.', 30],
    ['Taking a short break to grab a snack and recharge before continuing work.', 15],
    ["Updating the garden's inventory management system with current stock levels of seeds, fertilizers, and other supplies.", 25],
    ["Designing a new layout for the garden's trellis system to optimize space and promote healthy plant growth.", 35],
    ['Planning a workshop on sustainable gardening practices for the "Coffee & Community" fundraiser.', 30],
    ['Creating a schedule for regular water testing and maintenance of the irrigation system.', 20],
    ['Reviewing progress on the urban gardening project and making a to-do list for the next day.', 15],
    ["Making adjustments to the garden's pest control strategy based on recent observations of insect activity.", 25],
    ['Finalizing plans for the "Coffee & Community" fundraiser and coordinating with volunteers.', 30],
    ['Reviewing the urban gardening project budget and making adjustments as needed.', 10],
    ["Updating the garden's social media accounts with new content and engaging with followers.", 5],
    ['Wrapping up work on the urban gardening project for the day by documenting progress and setting reminders for next steps.', 15]
]